#!/data/data/com.termux/files/usr/bin/sh

PREFIX="/data/data/com.termux/files/usr"

if [ -x "${PREFIX}/bin/gtk-update-icon-cache" ]; then
    for i in $(find "${PREFIX}/share/icons" -type f -iname index.theme); do
        gtk-update-icon-cache $(dirname "${i}") > /dev/null 2>&1
    done
    unset i
fi

exit 0
